version: 2
jobs:
  unit_tests:
    working_directory: ~/StreakYC/GmailSDK
    parallelism: 1
    docker:
      - image: circleci/node:jessie-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dep-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v2-dep-{{ .Branch }}-
            - v2-dep-master-
            - v2-dep-
      - run: yarn
      - save_cache:
          key: v2-dep-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
            - ~/.yarn/bin/
            - ~/.config/yarn/global/
            - ~/.cache
      - run:
          name: Unit Tests
          command: yarn test
  integration:
    working_directory: ~/StreakYC/GmailSDK
    parallelism: 1
    docker:
      - image: circleci/node:jessie-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-integration-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v2-integration-{{ .Branch }}-
            - v2-integration-master-
            - v2-integration-
      - run: yarn
      - run:
          name: Build
          command: |
            if ! [ -n "$INBOXSDK_TEST_SECRET" ]; then exit; fi
            yarn gulp -s
      - run:
          name: Integration Test
          command: |
            if ! [ -n "$INBOXSDK_TEST_SECRET" ]; then exit; fi
            yarn puppeteer
      - save_cache:
          key: v2-integration-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
            - ~/.yarn/bin/
            - ~/.config/yarn/global/
            - ~/.cache
            - /tmp/jest_puppeteer_userDataDir

workflows:
  version: 2
  all_workflow:
    jobs:
      - unit_tests
      - integration
