version: 2
jobs:
  unit_tests:
    working_directory: ~/StreakYC/GmailSDK
    parallelism: 1
    docker:
      - image: streak/circleci:1
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_PASSWORD
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dep-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-dep-{{ .Branch }}-
            - v1-dep-master-
            - v1-dep-
      - run: yarn
      - save_cache:
          key: v1-dep-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
            - ~/.yarn/bin/
            - ~/.config/yarn/global/
            - ~/.cache
      - run:
          name: Unit Tests
          command: yarn test
  integration:
    working_directory: ~/StreakYC/GmailSDK
    parallelism: 1
    docker:
      - image: streak/circleci:1
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_PASSWORD
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-integration-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-integration-{{ .Branch }}-
            - v1-integration-master-
            - v1-integration-
      - run: yarn
      - run:
          name: Build
          command: |
            if ! [ -n "$INBOXSDK_TEST_SECRET" ]; then exit; fi
            yarn gulp -s
      - run:
          name: Integration Test
          command: |
            if ! [ -n "$INBOXSDK_TEST_SECRET" ]; then exit; fi
            yarn puppeteer
      - save_cache:
          key: v1-integration-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
            - ~/.yarn/bin/
            - ~/.config/yarn/global/
            - ~/.cache
            - /tmp/jest_puppeteer_userDataDir

workflows:
  version: 2
  all_workflow:
    jobs:
      - unit_tests
      - integration
